
# SPRING DATASOURCE CONFIGURATION

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HIKARI CONNECTION POOL CONFIGURATION

spring.datasource.hikari.pool-name=testConnection
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
#replace for 60000 for safety on prod
spring.datasource.hikari.leak-detection-threshold=300000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.auto-commit=true

# JPA / HIBERNATE CONFIGURATION

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# DATABASE INITIALIZATION

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data_1.sql, classpath:data_2.sql, classpath:data_3.sql, classpath:data_4.sql, classpath:data_5.sql, classpath:data_6.sql

# SECURITY CONFIGURATION

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# JWT CONFIGURATION

jwt.secret.access=${ACCEESS_SECRET}
jwt.secret.refresh=${REFRESH_SECRET}

# SPRINGDOC OPENAPI CONFIGURATION

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.api-docs.path=/v3/api-docs
springdoc.default-produces-media-type=application/json

# LOGGING CONFIGURATION

logging.level.org.hibernate.type=DEBUG
#logging.level.root=info
logging.level.org.springframework.security=ERROR
logging.level.org.springframework.web=ERROR
logging.level.com.asv.hotel=ERROR

#FILE FOR LOGGING IS logs/hotel-app  . ROTATING EVERY 30 DAYS AND 10MB

#logging.file.name=logs/hotel-app.log
#logging.logback.rollingpolicy.max-file-size=10MB
#logging.logback.rollingpolicy.max-history=30